config/routes.rb
Proyrails::Application.routes.draw do
  resources :productos

  get "usuario/index"

  get "estatico/about"

  get "estatico/contact"

  

end

app/models/producto.rb
class Producto < ActiveRecord::Base
  attr_accessible :description, :image_url, :price, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/estatico_controller.rb
class EstaticoController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @productos }
    end
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
    @producto = Producto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @producto }
    end
  end

  # GET /productos/new
  # GET /productos/new.json
  def new
    @producto = Producto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @producto }
    end
  end

  # GET /productos/1/edit
  def edit
    @producto = Producto.find(params[:id])
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(params[:producto])

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render json: @producto, status: :created, location: @producto }
      else
        format.html { render action: "new" }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /productos/1
  # PUT /productos/1.json
  def update
    @producto = Producto.find(params[:id])

    respond_to do |format|
      if @producto.update_attributes(params[:producto])
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto = Producto.find(params[:id])
    @producto.destroy

    respond_to do |format|
      format.html { redirect_to productos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/usuario_controller.rb
class UsuarioController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/estatico_helper.rb
module EstaticoHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/usuario_helper.rb
module UsuarioHelper
end

app/views/estatico/about.html.erb
<h1>Acerca de Nosotros</h1>
<p>Bienvenidos a ejercicio 1 © versión 0.80 (Sistema de Información ).

ejercico © versión 3.80.seg.ins le ofrece información amplia, rápida y totalmente actualizada sobre el Sistema de Información xxxx de la xxxxx. La información que se presenta esta destinada a las xxxxxxxxxxxxxxxxxxx.

El tipo de Información que se presenta esta relacionada con el SIS e incluye:  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.
Cualquier sugerencia por favor haganosla llegar a traves de la página de sugerencias. 
</p>

app/views/estatico/contact.html.erb
<h1>Contactanos</h1>
<p>En este espacio puede exponernos todas sus dudas comentarios y sugerencias acerca de la pagina, con mucho gusto evaluaremos y les responderemos sus preguntas. Gracias por escribirnos.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Proyrails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/productos/_form.html.erb
<%= form_for(@producto) do |f| %>
  <% if @producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% @producto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/productos/edit.html.erb
<h1>Editing producto</h1>

<%= render 'form' %>

<%= link_to 'Show', @producto %> |
<%= link_to 'Back', productos_path %>

app/views/productos/index.html.erb
<h1>Listing productos</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Image url</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @productos.each do |producto| %>
  <tr>
    <td><%= producto.title %></td>
    <td><%= producto.description %></td>
    <td><%= producto.image_url %></td>
    <td><%= producto.price %></td>
    <td><%= link_to 'Show', producto %></td>
    <td><%= link_to 'Edit', edit_producto_path(producto) %></td>
    <td><%= link_to 'Destroy', producto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Producto', new_producto_path %>

app/views/productos/new.html.erb
<h1>New producto</h1>

<%= render 'form' %>

<%= link_to 'Back', productos_path %>

app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @producto.title %>
</p>

<p>
  <b>Description:</b>
  <%= @producto.description %>
</p>

<p>
  <b>Image url:</b>
  <%= @producto.image_url %>
</p>

<p>
  <b>Price:</b>
  <%= @producto.price %>
</p>


<%= link_to 'Edit', edit_producto_path(@producto) %> |
<%= link_to 'Back', productos_path %>

app/views/usuario/index.html.erb
<h1>Usuario#index</h1>
<p>Find me in app/views/usuario/index.html.erb</p>